export class AppConst {
    public static servidorPath = 'http://localhost:8181';

    public static provincias = {
        "ALV": "ÁLAVA",
        "ALB": "ALBACETE",
        "ALI": "ALICANTE",
        "ALM": "ALMERÍA",
        "AST": "ASTURIAS",
        "AVL": "ÁVILA",
        "BAD": "BADAJOZ",
        "BAR": "BARCELONA",
        "BUR": "BURGOS",
        "CAC": "CÁCERES",
        "CAD": "CÁDIZ",
        "CAN": "CANTABRIA",
        "CAS": "CASTELLÓN",
        "CIR": "CIUDAD REAL",
        "COR": "CÓRDOBA",
        "CUE": "CUENCA",
        "GER": "GERONA",
        "GRA": "GRANADA",
        "GUA": "GUADALAJARA",
        "GUI": "GUIPUZKOA",
        "HUE": "HUELVA",
        "HUS": "HUESCA",
        "ISB": "ISLAS BALEARES",
        "JAE": "JAÉN",
        "LAC": "LA CORUÑA",
        "LAR": "LA RIOJA",
        "LAP": "LAS PALMAS",
        "LEO": "LEÓN",
        "LER": "LÉRIDA",
        "LUG": "LUGO",
        "MAD": "MADRID",
        "MAL": "MÁLAGA",
        "MUR": "MURCIA",
        "NAV": "NAVARRA",
        "ORE": "ORENSE",
        "PAL": "PALENCIA",
        "PON": "PONTEVEDRA",
        "SAL": "SALAMANCA",
        "SEG": "SEGOVIA",
        "SEV": "SEVILLA",
        "SOR": "SORIA",
        "TAR": "TARRAGONA",
        "TEN": "TENERIFE",
        "TER": "TERUEL",
        "TOL": "TOLEDO",
        "VAL": "VALENCIA",
        "VLL": "VALLADOLID",
        "VIZ": "VIZCAYA",
        "ZAM": "ZAMORRA",
        "ZAR": "ZARAGOZA"
    };
}
